export const dummyData = [
    { event: "user_registered", distinctId: "user_1", properties: { source: "landing_page" } },
    { event: "user_logged_in", distinctId: "user_1", properties: { device: "ios" } },
    { event: "dashboard_viewed", distinctId: "user_1", properties: { page: "home" } },
    { event: "session_started", distinctId: "user_1" },
    { event: "session_ended", distinctId: "user_1" },
    { event: "project_created", distinctId: "user_1", properties: { name: "Project A" } },
    { event: "task_created", distinctId: "user_1", properties: { task: "Setup repo" } },
    { event: "task_completed", distinctId: "user_1", properties: { task: "Setup repo" } },
    { event: "payment_success", distinctId: "user_1", properties: { amount: 499 } },
    { event: "plan_upgraded", distinctId: "user_1", properties: { plan: "Pro" } },

    { event: "user_registered", distinctId: "user_2", properties: { source: "referral" } },
    { event: "user_logged_in", distinctId: "user_2" },
    { event: "dashboard_viewed", distinctId: "user_2" },
    { event: "session_started", distinctId: "user_2" },
    { event: "task_created", distinctId: "user_2", properties: { task: "Fix bug #12" } },
    { event: "task_completed", distinctId: "user_2", properties: { task: "Fix bug #12" } },
    { event: "project_created", distinctId: "user_2", properties: { name: "Work Project" } },
    { event: "payment_success", distinctId: "user_2", properties: { amount: 999 } },
    { event: "plan_renewed", distinctId: "user_2", properties: { plan: "Pro" } },
    { event: "most_used_feature", distinctId: "user_2", properties: { feature: "Dashboard" } },

    { event: "user_registered", distinctId: "user_3" },
    { event: "user_logged_in", distinctId: "user_3" },
    { event: "session_started", distinctId: "user_3" },
    { event: "dashboard_viewed", distinctId: "user_3" },
    { event: "project_created", distinctId: "user_3", properties: { name: "Startup Idea" } },
    { event: "task_created", distinctId: "user_3", properties: { task: "Brainstorm" } },
    { event: "task_completed", distinctId: "user_3", properties: { task: "Brainstorm" } },
    { event: "most_used_feature", distinctId: "user_3", properties: { feature: "Tasks" } },
    { event: "session_ended", distinctId: "user_3" },
    { event: "plan_renewed", distinctId: "user_3", properties: { plan: "Basic" } },

    { event: "user_registered", distinctId: "user_4" },
    { event: "user_logged_in", distinctId: "user_4" },
    { event: "session_started", distinctId: "user_4" },
    { event: "dashboard_viewed", distinctId: "user_4" },
    { event: "task_created", distinctId: "user_4", properties: { task: "Refactor UI" } },
    { event: "task_completed", distinctId: "user_4", properties: { task: "Refactor UI" } },
    { event: "payment_success", distinctId: "user_4", properties: { amount: 699 } },
    { event: "plan_upgraded", distinctId: "user_4", properties: { plan: "Ultimate" } },
    { event: "session_ended", distinctId: "user_4" },
    { event: "most_used_feature", distinctId: "user_4", properties: { feature: "Projects" } },

    { event: "user_registered", distinctId: "user_5" },
    { event: "user_logged_in", distinctId: "user_5" },
    { event: "session_started", distinctId: "user_5" },
    { event: "dashboard_viewed", distinctId: "user_5" },
    { event: "project_created", distinctId: "user_5", properties: { name: "Client Work" } },
    { event: "task_created", distinctId: "user_5", properties: { task: "Email client" } },
    { event: "task_completed", distinctId: "user_5", properties: { task: "Email client" } },
    { event: "plan_renewed", distinctId: "user_5" },
    { event: "session_ended", distinctId: "user_5" },
    { event: "most_used_feature", distinctId: "user_5", properties: { feature: "Dashboard" } }
]